### PR TITLE
[4.x] Support for Ruby 3

### PR DESCRIPTION
**Pull request by pedrofurtado**
@adzap  Support for Ruby 3 in 4.x versions 🎉 🤝 

c/c: @willradi @leonardocomar 🍻

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@adzap Your eyes/review on it will be awesome 🤝

**Comment by StoneGod** [comment]
Hi, what about merge and release this fix?

**Comment by StoneGod** [comment]
Anybody here?

**Comment by adzap** [comment]
v4 is for Rails 4.x Does Rails v4.x support Ruby 3?

**Comment by pedrofurtado** [comment]
We use this gem in 4.x version with Rails 6 👍

**Comment by pedrofurtado** [comment]
But now with 5.x official version released, the suggestion is to migrate to 5.x, right @adzap ?

is there any breaking change betwenn 4.x and 5.x version of gem? Changelog provides this informations for us?

Anyway, thanks a lot for your feedback here ❤️ 🤝

**Comment by adzap** [comment]
Yes v5 is official Rails 5 release and removes some old hacks.

**Comment by pedrofurtado** [comment]
@adzap  Anyway, is it possible to provide this feature to 4.x? Currently, we are using a fork to provide this🤝

**Comment by adzap** [comment]
@pedrofurtado the changes are backward incompatible and specific to changes in Rails mostly ActiveModel and ActiveRecord.

**Pull request closed without merging**
