### PR TITLE
ActiveRecord::Base.default_timezone is deprecated, move to ActiveRecord.default_timezone

### PR DESCRIPTION
**Pull request by timburgan**
Using `validates_timeliness` in Rails 7.0alpha returns:

```
ActiveRecord::Base.default_timezone is deprecated, move to ActiveRecord.default_timezone
```

so, doing that.

### CODE REVIEW

**Comment by pedrofurtado** [comment]
Thanks for your contribution, @timburgan ! 🎉 

Happy to see Rails 7 released officially!

Pinging @adzap for notification

**Comment by EQuincerot** [comment]
As rails 7 has been released, what is missing now, to merge this PR? :)
Could I help anyhow?

**Comment by EQuincerot** [comment]
I'm sorry to insist @adzap but would it be possible to merge and realease this pull request? that would be so nice

**Comment by adzap** [comment]
Thanks. It's been implemented in other commits.

**Pull request closed without merging**
