### PR TITLE
Update due deprecation for rails 7.0

### PR DESCRIPTION
**Pull request by camilova**

### CODE REVIEW

**Comment by Laykou** [comment]
@adzap Can this be merged and released as new version please?

**Comment by nataliastanko** [comment]
[.gemspec](https://github.com/adzap/validates_timeliness/blob/1899a040ff7e0a984d40d9cf3813b62081ed0945/validates_timeliness.gemspec#L20) has activemodel locked to versions < 7 so your suggested change wouldn't work. 

The new suggested change: 
```shell
$rails c
Eager loading is enabled. New files might not have any effect until the app is restarted.
Running via Spring preloader in process 11917
Loading development environment (Rails 6.1.4.4)
irb(main):001:0> ActiveRecord.default_timezone
(irb):1:in `<main>': undefined method `default_timezone' for ActiveRecord:Module (NoMethodError)
irb(main):002:0> 
```
does not work with Rails 6.

I suggest changing the activemodel dependency to the following:
`s.add_runtime_dependency("activemodel", [">= 7", "< 8"])`

**Comment by camilova** [comment]
Hi @nataliastanko, changing runtime dependency will not solve this, but it is needed too. I simply made a ternary to switch method to call and make it retrocompatible.

**Comment by berkos** [comment]
👋 Thanks for the work into this. 🙏 
 I was wondering if this PR is needed? I can see there is already [an open PR](https://github.com/adzap/validates_timeliness/pull/213) addressing Rails 7 which would be great if it can be merged.

**Pull request closed without merging**
