### PR TITLE
Update README.rdoc with the suggestion of a gem with i18n translations

### PR DESCRIPTION
**Pull request by pedrofurtado**
@adzap PR: Update README.rdoc with the suggestion of a gem with i18n translations

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@adzap Is this PR ready for merge?

**Comment by pedrofurtado** [comment]
@adzap Is this PR ready for merge?

**Comment by pedrofurtado** [comment]
@adzap Is this PR ready for merge?

**Comment by pedrofurtado** [comment]
@adzap Any news?

**Comment by adzap** [comment]
I am happy to put a mention in the README, but how you have it in this PR. The support for i18n is not dependent on a gem. But your gem might be a big time saver for many people so I suggest changing it to the following:

```rdoc
* Supports I18n for the error messages. For multi-language support try {timeliness-i18n gem}[https://github.com/pedrofurtado/timeliness-i18n].)
```

**Comment by pedrofurtado** [comment]
@adzap Thanks for feedback! I've made the change suggested by you.

**Pull request merged**
