### PR TITLE
Splat message options when doing ActiveModel errors.add

### PR DESCRIPTION
**Pull request by schinery**
Fix for https://github.com/adzap/validates_timeliness/issues/204

### CODE REVIEW

**Comment by adzap** [comment]
Thanks but the validator specs should cover it given it add errors internally and the issue should have showed up already. I'm interested in why it hadn't.

**Comment by schinery** [comment]
@adzap is it worth setting up GitHub actions to run the specs for Ruby 2.7 and 3?

**Comment by adzap** [comment]
Yes. Looks like we need to move off Travis to GitHub actions anyway. Any help in doing that would be appreciated.

**Comment by schinery** [comment]
@adzap sure thing, I've added the config for GitHub actions to run the tests as part of this PR (if that's cool?) and threw in the Dependabot config too.

[Here](https://github.com/schinery/validates_timeliness/actions/runs/1507664522) are the specs running for both Ruby 2.7 and 3.0.

**Comment by adzap** [comment]
Excellent thanks! So ruby 3.0 is passing. Weird.

Do you know how to add the appraisal gemfiles into the actions matrix?

**Comment by adzap** [comment]
Ignore me I was looking this on my phone and now realise it's part of the PR to fix it also. I will merge.

**Pull request merged**
